TrajectoryPlannerROS:

  # Robot Configuration Parameters
  holonomic_robot: false

  # Forward Simulation Parameters
  sim_time: 1.0

  # Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 3.0
