TrajectoryPlannerROS:

  # Robot Configuration Parameters
  acc_lim_x: 1.0 #new
  holonomic_robot: false

  # Forward Simulation Parameters
  sim_time: 10.0 #20.0
  controller_frequency: 4.0
    
  # Trajectory Scoring Parameters
  meter_scoring: true
