TrajectoryPlannerROS:

  # Robot Configuration Parameters
  acc_lim_x: 1.0 
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  max_vel_x: 0.9
  min_vel_x: 0.1
  max_vel_theta: 0.8
  min_vel_theta: -0.8
  holonomic_robot: false

  # Forward Simulation Parameters
  sim_time: 1.0
  controller_frequency: 4.0
    
  # Trajectory Scoring Parameters
  meter_scoring: true
