map_type: costmap

footprint: [[0.25, 0.175], [0.25, -0.175], [-0.25, -0.175], [-0.25, 0.175]]

# Coordinate frame and tf parameters
transform_tolerance: 0.5

# Obstacle Map Layer
observation_sources: laser_scan_sensor
obstacle_range: 2.0
raytrace_range: 3.0

# Inflation Layer
inflation_radius: 0.65

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /my_robot/laser/scan, marking: true, clearing: true}

