global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   # Decrease if If you received warning on Transform Timeout and Map Update Loop
   update_frequency: 2.5 # 0.25 # default 5.0
   publish_frequency: 2.5 # 0.25 # default 0.0
   width: 40.0
   height: 40.0
   resolution: 0.05
   static_map: true
   rolling_window: false
