global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   
   # Reduce if you receive warning on 'Transform Timeout' and 'Map Update Loop'
   update_frequency: 2.5
   publish_frequency: 2.5
   
   width: 30.0
   height: 30.0
   resolution: 0.05
   static_map: true
   rolling_window: false
