local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint

   # Reduce if you receive warning on 'Transform Timeout' and 'Map Update Loop'
   update_frequency: 2.5
   publish_frequency: 2.5

   width: 10.0
   height: 10.0
   resolution: 0.05

   # The LOCAL static map keeps changing
   static_map: false
   rolling_window: true
