local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   # Decrease update_frequency & publish_frequency, if you received warning on Transform Timeout and Map Update Loop
   update_frequency: 2.5
   publish_frequency: 2.5
   width: 10.0
   height: 10.0
   resolution: 0.05
   # the LOCAL static map keeps changing
   static_map: false
   rolling_window: true
